{% set python_min = "3.10" %}
{% set name = "cmip7-repack" %}
{% set version = "1.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/c/cmip7_repack/cmip7_repack-{{ version }}.tar.gz
  sha256: 25b33cd147dd16b5ff287dcb6d0ce6997f1b95065144d71e88c2a2e272ac9414

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip !=21.3
    - setuptools >=80
    - setuptools_scm >=8
  run:
    - python >={{ python_min }}
    - pip
    - hdf5
    - packaging
    - pyfive >=1.1.1
    - __linux   # [linux]
    - __osx     # [osx]

test:
  # needs all pytests when we have correct test suite
  # source_files:
  #   - tests
  requires:
    - python {{ python_min }}
    - pip
  commands:
    - pip check
    - cmip7repack -h

about:
  home: https://github.com/NCAS-CMS/cmip7_repack
  license: 'BSD-3-Clause'
  license_file: LICENSE
  summary: 'Repacking to different chunking and metadata layout tool for CMIP7 data.'

extra:
  recipe-maintainers:
    - davidhassell
    - valeriupredoi
